# Generated by Django 2.0.8 on 2019-02-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course/%Y%m%d'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='offline',
            field=models.BooleanField(default=True, verbose_name='是否上线'),
        ),
    ]
