# Generated by Django 2.0.8 on 2019-03-05 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20190228_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courselist',
            old_name='title',
            new_name='titles',
        ),
    ]
