# Generated by Django 2.0.8 on 2019-02-15 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='ids',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL, verbose_name='发消息用户'),
        ),
    ]
