# Generated by Django 2.0.8 on 2019-02-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190215_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='is_supper',
            field=models.BooleanField(default=False, verbose_name='是系统消息'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='ids',
            field=models.UUIDField(blank=True, null=True, verbose_name='评论文章id'),
        ),
    ]
