# Generated by Django 2.0.8 on 2018-12-26 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20181225_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='添加时间'),
        ),
    ]
