# Generated by Django 2.0.8 on 2019-03-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190218_1500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermessage',
            options={'ordering': ('-add_time',), 'verbose_name': '用户消息', 'verbose_name_plural': '用户消息'},
        ),
        migrations.AlterField(
            model_name='user',
            name='user_imag',
            field=models.ImageField(blank=True, default='', null=True, upload_to='user/%Y%m%d', verbose_name='用户头像'),
        ),
    ]
