# Generated by Django 2.0.8 on 2019-01-22 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20181226_0949'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follow',
            new_name='Follows',
        ),
        migrations.AlterModelOptions(
            name='follows',
            options={'ordering': ('-follow',)},
        ),
    ]
