# Generated by Django 2.0.8 on 2019-01-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190122_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='info',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='个人介绍'),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='职位'),
        ),
    ]
