# Generated by Django 2.0.8 on 2019-03-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_oauthqq'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
