# Generated by Django 2.0.8 on 2019-01-23 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190123_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='add_time',
        ),
    ]
