# Generated by Django 2.0.8 on 2019-03-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='message',
            field=models.TextField(verbose_name='消息内容'),
        ),
    ]
