# Generated by Django 2.0.8 on 2019-03-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20190326_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='地址'),
        ),
    ]
