# Generated by Django 2.0.8 on 2019-01-23 05:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_user_add_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verifycode',
            options={'verbose_name': '邮箱验证码', 'verbose_name_plural': '邮箱验证码'},
        ),
        migrations.RemoveField(
            model_name='verifycode',
            name='add_time',
        ),
        migrations.RemoveField(
            model_name='verifycode',
            name='mobile',
        ),
        migrations.AddField(
            model_name='verifycode',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='verifycode',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='发送时间'),
        ),
        migrations.AddField(
            model_name='verifycode',
            name='send_type',
            field=models.CharField(choices=[('register', '注册'), ('forget', '找回密码'), ('update_email', '修改邮箱')], default='forget', max_length=30, verbose_name='验证码类型'),
        ),
    ]
