# Generated by Django 2.0.12 on 2019-08-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_seo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seo',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='seo',
            name='keywords',
            field=models.TextField(),
        ),
    ]
