# Generated by Django 2.0.8 on 2018-12-20 09:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article_add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('keywords', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=400)),
                ('list_pic', models.ImageField(upload_to='article/list_pic/%Y/%m/%d')),
                ('content', models.TextField()),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
                ('authors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
