# Generated by Django 2.0.4 on 2018-12-21 13:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_add',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='article_add',
            name='list_pic',
            field=models.ImageField(blank=True, null=True, upload_to='article/%Y%m%d'),
        ),
    ]
