# Generated by Django 2.0.8 on 2018-12-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_add',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
