# Generated by Django 2.0.8 on 2019-02-27 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20190227_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_article',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
