# Generated by Django 2.0.8 on 2018-12-28 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20181221_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_comment',
            name='aomments_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='article.Article_Comment'),
        ),
        migrations.AlterField(
            model_name='article_comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
