# Generated by Django 2.0.8 on 2018-12-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20181220_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_add',
            name='desc',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='article_add',
            name='keywords',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
