# Generated by Django 2.0.8 on 2018-12-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20181220_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_add',
            name='list_pic',
            field=models.ImageField(blank=True, null=True, upload_to='article/list_pic/%Y/%m/%d'),
        ),
    ]
