# Generated by Django 2.0.8 on 2019-01-03 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20181228_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article_comment',
            name='article',
        ),
        migrations.AddField(
            model_name='article_add',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Article_Comment', verbose_name='文章'),
        ),
        migrations.AlterField(
            model_name='article_add',
            name='authors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='article_add',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Category_Article', verbose_name='分类'),
        ),
    ]
