# Generated by Django 2.0.8 on 2019-03-13 14:01

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20190227_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Headlines',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('category', models.CharField(max_length=20, verbose_name='分类')),
                ('author_name', models.CharField(max_length=100, verbose_name='来源')),
                ('url', models.URLField()),
                ('pic', models.URLField()),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
        ),
    ]
