# Generated by Django 2.0.8 on 2019-01-03 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20190103_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article_add',
            name='comments',
        ),
        migrations.AddField(
            model_name='article_comment',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Article_add', verbose_name='文章'),
        ),
    ]
