# Generated by Django 2.0.8 on 2019-03-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20190314_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='headlines',
            name='conent',
            field=models.TextField(default='', verbose_name='内容'),
        ),
    ]
