# Generated by Django 2.0.8 on 2019-01-08 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20190108_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecommentreply',
            name='aomments_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Article_Comment'),
        ),
    ]
