# Generated by Django 2.0.8 on 2019-04-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20190314_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_comment',
            name='url',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='articlecommentreply',
            name='url',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
    ]
