# Generated by Django 2.0.8 on 2019-01-08 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20190108_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_comment',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='articlecommentreply',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='article_comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Article_add', verbose_name='文章'),
        ),
        migrations.AlterField(
            model_name='articlecommentreply',
            name='aomments_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Article_Comment'),
        ),
    ]
