# Generated by Django 2.0.8 on 2019-01-08 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0008_auto_20190108_1345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article_comment',
            options={'ordering': ('-add_time',), 'verbose_name': '文章评论', 'verbose_name_plural': '文章评论'},
        ),
        migrations.AddField(
            model_name='articlecommentreply',
            name='to_uid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='to_uid', to=settings.AUTH_USER_MODEL, verbose_name='目标用户'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articlecommentreply',
            name='aomments_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Article_Comment', verbose_name='回复id'),
        ),
        migrations.AlterField(
            model_name='articlecommentreply',
            name='comments',
            field=models.TextField(verbose_name='回復内容'),
        ),
        migrations.AlterField(
            model_name='articlecommentreply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_uid', to=settings.AUTH_USER_MODEL, verbose_name='当前用户'),
        ),
    ]
