# Generated by Django 2.0.8 on 2019-01-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20190108_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecommentreply',
            name='comments',
            field=models.TextField(verbose_name='回复内容'),
        ),
    ]
