# Generated by Django 2.0.12 on 2019-09-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20190802_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_article',
            name='order',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
    ]
