# Generated by Django 2.0.8 on 2019-01-08 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0010_auto_20190108_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecommentreply',
            name='to_uid',
        ),
        migrations.AddField(
            model_name='articlecommentreply',
            name='to_uids',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='to_uids', to=settings.AUTH_USER_MODEL, verbose_name='目标用户'),
        ),
    ]
