# Generated by Django 2.0.8 on 2019-01-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_auto_20190108_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_add',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='是否显示'),
        ),
    ]
