# Generated by Django 2.0.8 on 2019-01-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_article_add_is_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_add',
            name='is_Recommend',
            field=models.BooleanField(default=False, verbose_name='是否推荐'),
        ),
        migrations.AlterField(
            model_name='article_add',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='是否删除'),
        ),
    ]
