# Generated by Django 2.0.8 on 2019-01-21 07:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0013_auto_20190121_1522'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article_add',
            new_name='Article',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='is_Recommend',
            new_name='is_recommend',
        ),
    ]
