# Generated by Django 2.0.12 on 2020-06-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamiccategory',
            name='name',
        ),
        migrations.AddField(
            model_name='dynamic',
            name='name',
            field=models.ManyToManyField(to='dynamic.dynamicCategory'),
        ),
    ]
