# Generated by Django 2.0.8 on 2019-03-27 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('content', models.TextField(verbose_name='内容')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='发布日期')),
                ('hidden', models.BooleanField(default=False, verbose_name='是否隐藏')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '帖子表',
                'verbose_name_plural': '帖子表',
            },
        ),
        migrations.CreateModel(
            name='Forum_plate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='板块名称')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '论坛版块',
                'verbose_name_plural': '论坛版块',
            },
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='发布日期')),
                ('stick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Forum')),
            ],
            options={
                'verbose_name': '置顶',
                'verbose_name_plural': '置顶',
            },
        ),
        migrations.AddField(
            model_name='forum',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Forum_plate', verbose_name='板块名称'),
        ),
    ]
