# Generated by Django 2.0.8 on 2019-03-27 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum_plate',
            name='category_type',
            field=models.IntegerField(choices=[(1, '一级类目'), (2, '二级类目'), (3, '三级类目')], default=1, help_text='类目级别', verbose_name='类目级别'),
        ),
        migrations.AddField(
            model_name='forum_plate',
            name='code',
            field=models.CharField(default='', help_text='类别code', max_length=30, verbose_name='类别code'),
        ),
        migrations.AddField(
            model_name='forum_plate',
            name='parent_category',
            field=models.ForeignKey(blank=True, help_text='父类目级', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='forum.Forum_plate', verbose_name='父类目级'),
        ),
    ]
