# Generated by Django 2.0.8 on 2019-04-01 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20190327_1647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forum',
            options={'ordering': ('-add_time',), 'verbose_name': '帖子表', 'verbose_name_plural': '帖子表'},
        ),
        migrations.AlterModelOptions(
            name='forum_plate',
            options={'ordering': ('-add_time',), 'verbose_name': '论坛版块', 'verbose_name_plural': '论坛版块'},
        ),
    ]
