# Generated by Django 2.0.8 on 2019-04-01 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20190401_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forum',
            old_name='author',
            new_name='authors',
        ),
    ]
