# Generated by Django 2.0.8 on 2019-04-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20190401_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='关键字'),
        ),
    ]
