# Generated by Django 2.0.8 on 2019-04-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_forum_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='click_nums',
            field=models.PositiveIntegerField(default=0, verbose_name='阅读数量'),
        ),
    ]
