# Generated by Django 2.0.8 on 2019-04-02 10:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0008_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentCommentReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(verbose_name='回复内容')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='地址')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-add_time',), 'verbose_name': '帖子回复表', 'verbose_name_plural': '帖子回复表'},
        ),
        migrations.AddField(
            model_name='commentcommentreply',
            name='aomments_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Comment', verbose_name='回复id'),
        ),
        migrations.AddField(
            model_name='commentcommentreply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='当前用户'),
        ),
    ]
