# Generated by Django 2.0.8 on 2019-04-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_auto_20190408_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='url',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='parent_comment',
            name='url',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
    ]
