# Generated by Django 2.0.8 on 2019-04-15 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0014_auto_20190408_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum_click',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbs', models.IntegerField(default=0)),
                ('forums', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Forum', verbose_name='帖子')),
            ],
        ),
    ]
