# Generated by Django 2.0.12 on 2019-04-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0015_forum_click'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发布日期'),
        ),
    ]
