# Generated by Django 2.0.12 on 2019-07-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0016_auto_20190430_1528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parent_comment',
            options={'verbose_name': '帖子回复表', 'verbose_name_plural': '帖子回复表'},
        ),
        migrations.AddField(
            model_name='forum_plate',
            name='image',
            field=models.ImageField(blank=True, upload_to='forum/%Y%m%d', verbose_name='图标'),
        ),
    ]
