# Generated by Django 2.0.12 on 2019-08-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0017_auto_20190730_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
